/** Realistic demo user profiles — index 0 maps to video 1, etc. */
module.exports = [
  { fullName: 'Aisha Rahman', username: 'aisha_rahman', job: 'UI/UX Designer', bio: 'Designing interfaces that feel effortless. Coffee enthusiast & weekend hiker.', city: 'Karachi', maritalStatus: 'Unmarried', dateOfBirth: '1997-06-14', school: 'Karachi Grammar School', college: 'DHA Degree College', university: 'Indus Valley School of Art & Architecture' },
  { fullName: 'Omar Farooq', username: 'omar_farooq', job: 'Software Engineer', bio: 'Building scalable systems by day, open-source contributor by night.', city: 'Lahore', maritalStatus: 'Married', dateOfBirth: '1995-11-20', school: 'Aitchison College', college: 'Govt College University', university: 'LUMS (Lahore University of Management Sciences)' },
  { fullName: 'Sarah Ahmed', username: 'sarah_ahmed', job: 'Content Creator & Strategist', bio: 'Storyteller through lens and words. Always chasing golden hour.', city: 'Islamabad', maritalStatus: 'Unmarried', dateOfBirth: '1998-03-08', school: 'Beaconhouse School System', college: 'Islamabad College for Girls', university: 'NUST Islamabad' },
  { fullName: 'Ali Khan', username: 'ali_khan', job: 'Travel Photographer', bio: 'Capturing landscapes from 40+ countries. Next stop: Patagonia.', city: 'Dubai', maritalStatus: 'Married', dateOfBirth: '1993-09-15', school: 'St. Patrick High School', college: 'American University in Dubai', university: 'Middlesex University Dubai' },
  { fullName: 'Fatima Noor', username: 'fatima_noor', job: 'Fashion Stylist & Consultant', bio: 'Minimalist wardrobe curator. Sustainable fashion advocate.', city: 'London', maritalStatus: 'Unmarried', dateOfBirth: '1996-12-01', school: 'Highgate School', college: 'London Fashion College', university: 'Central Saint Martins' },
  { fullName: 'Hamza Malik', username: 'hamza_malik', job: 'Fitness & Performance Coach', bio: 'Helping people move better. No shortcuts, just consistency.', city: 'Toronto', maritalStatus: 'Married', dateOfBirth: '1994-07-22', school: 'St. Michael College School', college: 'Seneca College', university: 'University of Toronto' },
  { fullName: 'Zara Siddiqui', username: 'zara_siddiqui', job: 'Digital Artist & 3D Animator', bio: 'Pixels, paint & motion. Creating worlds one frame at a time.', city: 'San Francisco', maritalStatus: 'Unmarried', dateOfBirth: '1999-01-19', school: 'Lowell High School', college: 'City College of San Francisco', university: 'California College of the Arts' },
  { fullName: 'Bilal Hussain', username: 'bilal_hussain', job: 'Music Producer & Sound Engineer', bio: 'Beats that breathe. Lo-fi by night, studio sessions by day.', city: 'Berlin', maritalStatus: 'Unmarried', dateOfBirth: '1995-04-30', school: 'John F. Kennedy School', college: 'BIMM University Berlin', university: 'Berlin University of the Arts' },
  { fullName: 'Maya Patel', username: 'maya_patel', job: 'Food Blogger & Culinary Consultant', bio: 'Spice routes & street food adventures. Always hungry for more.', city: 'Mumbai', maritalStatus: 'Married', dateOfBirth: '1994-10-12', school: 'Cathedral and John Connon School', college: 'St. Xavier’s College', university: 'University of Mumbai' },
  { fullName: 'Ryan Chen', username: 'ryan_chen', job: 'Product Manager', bio: 'Shipping products people love. User research nerd.', city: 'Seattle', maritalStatus: 'Married', dateOfBirth: '1992-08-25', school: 'Garfield High School', college: 'Bellevue College', university: 'University of Washington' },
  { fullName: 'Elena Vasquez', username: 'elena_vasquez', job: 'Senior Architect', bio: 'Spaces that inspire. Brutalist aesthetics with warm interiors.', city: 'Barcelona', maritalStatus: 'Unmarried', dateOfBirth: '1996-05-18', school: 'Colegio Montserrat', college: 'Barcelona Institute of Architecture', university: 'Universitat Politècnica de Catalunya' },
  { fullName: "James O'Brien", username: 'james_obrien', job: 'Investigative Journalist', bio: 'Investigative stories & long-form features. Truth over clicks.', city: 'Dublin', maritalStatus: 'Married', dateOfBirth: '1991-02-14', school: 'Gonzaga College SJ', college: 'Dublin Institute of Technology', university: 'Trinity College Dublin' },
  { fullName: 'Priya Sharma', username: 'priya_sharma', job: 'Yoga Instructor & Wellness Coach', bio: 'Mindful movement & breathwork. Teaching since 2015.', city: 'Goa', maritalStatus: 'Unmarried', dateOfBirth: '1997-08-05', school: 'Sharada Mandir School', college: 'Dhempe College of Arts & Science', university: 'Goa University' },
  { fullName: 'Marcus Johnson', username: 'marcus_johnson', job: 'Street Photographer', bio: 'Candid moments in urban chaos. Black & white soul.', city: 'Chicago', maritalStatus: 'Unmarried', dateOfBirth: '1995-03-29', school: 'Whitney Young Magnet High School', college: 'Columbia College Chicago', university: 'School of the Art Institute of Chicago' },
  { fullName: 'Leila Hassan', username: 'leila_hassan', job: 'Interior Designer', bio: 'Transforming rooms into sanctuaries. Plants are non-negotiable.', city: 'Cairo', maritalStatus: 'Married', dateOfBirth: '1994-11-17', school: 'Cairo American College', college: 'Misr International University', university: 'The American University in Cairo' },
  { fullName: 'Daniel Kim', username: 'daniel_kim', job: 'Lead Game Developer', bio: 'Indie dev crafting narrative adventures. Unity & Unreal.', city: 'Seoul', maritalStatus: 'Unmarried', dateOfBirth: '1996-09-03', school: 'Seoul Science High School', college: 'KAIST Academy', university: 'Seoul National University' },
  { fullName: 'Sofia Rodriguez', username: 'sofia_rodriguez', job: 'Professional Makeup Artist', bio: 'Glam, editorial & bridal. Making confidence visible.', city: 'Mexico City', maritalStatus: 'Unmarried', dateOfBirth: '1998-07-21', school: 'Colegio Madrid', college: 'Centro de Diseño y Cine', university: 'Universidad Iberoamericana' },
  { fullName: 'Ethan Brooks', username: 'ethan_brooks', job: 'Startup Founder & Tech Executive', bio: 'Building the future of remote work. Third-time founder.', city: 'Austin', maritalStatus: 'Married', dateOfBirth: '1990-10-31', school: 'Westlake High School', college: 'Austin Community College', university: 'University of Texas at Austin' },
  { fullName: 'Nadia Ibrahim', username: 'nadia_ibrahim', job: 'Pediatric Healthcare Specialist', bio: 'Caring for little warriors. Advocate for healthcare access.', city: 'Amman', maritalStatus: 'Married', dateOfBirth: '1995-01-26', school: 'Amman National School', college: 'Princess Muna College of Nursing', university: 'University of Jordan' },
  { fullName: 'Tyler Nguyen', username: 'tyler_nguyen', job: 'Cinematographer & Director', bio: 'Cinematic storytelling for brands & artists.', city: 'Los Angeles', maritalStatus: 'Unmarried', dateOfBirth: '1996-04-09', school: 'Beverly Hills High School', college: 'Santa Monica College', university: 'USC School of Cinematic Arts' },
  { fullName: 'Amara Okafor', username: 'amara_okafor', job: 'Author & Spoken Word Poet', bio: 'Words woven from lived experience. Published in 12 anthologies.', city: 'Lagos', maritalStatus: 'Unmarried', dateOfBirth: '1997-12-11', school: 'Corona Secondary School', college: 'Yaba College of Technology', university: 'University of Lagos' },
  { fullName: 'Lucas Fernandez', username: 'lucas_fernandez', job: 'Specialty Coffee Roaster', bio: 'Third-wave barista. Single-origin obsessive.', city: 'Melbourne', maritalStatus: 'Married', dateOfBirth: '1993-06-17', school: 'Melbourne High School', college: 'RMIT TAFE', university: 'University of Melbourne' },
  { fullName: 'Hannah Wright', username: 'hannah_wright', job: 'Environmental Data Scientist', bio: 'Climate data & community action. Ocean conservation volunteer.', city: 'Vancouver', maritalStatus: 'Unmarried', dateOfBirth: '1996-08-30', school: 'Lord Byng Secondary School', college: 'Langara College', university: 'University of British Columbia' },
  { fullName: 'Imran Qureshi', username: 'imran_qureshi', job: 'High Performance Sports Coach', bio: 'Developing young talent. Former domestic player.', city: 'Multan', maritalStatus: 'Married', dateOfBirth: '1992-05-04', school: 'La Salle Higher Secondary School', college: 'Emerson College Multan', university: 'Bahauddin Zakariya University' },
  { fullName: 'Chloe Bennett', username: 'chloe_bennett', job: 'Literary Critic & Editor', bio: '300+ books read this decade. Fiction & memoir enthusiast.', city: 'Edinburgh', maritalStatus: 'Unmarried', dateOfBirth: '1997-02-23', school: 'George Heriot’s School', college: 'Edinburgh College', university: 'University of Edinburgh' },
  { fullName: 'Arjun Mehta', username: 'arjun_mehta', job: 'Lead Data Analyst', bio: 'Turning numbers into narratives. Python & visualization.', city: 'Bangalore', maritalStatus: 'Married', dateOfBirth: '1994-03-16', school: 'National Public School', college: 'St. Joseph’s College', university: 'Indian Institute of Science (IISc)' },
  { fullName: 'Isabelle Laurent', username: 'isabelle_laurent', job: 'Executive Pastry Chef', bio: 'French techniques, global flavors. Croissants are my love language.', city: 'Paris', maritalStatus: 'Unmarried', dateOfBirth: '1995-10-08', school: 'Lycée Henri-IV', college: 'Ferrandi Paris', university: 'Le Cordon Bleu Paris' },
  { fullName: 'Noah Thompson', username: 'noah_thompson', job: 'Action Sports Creator', bio: 'Street & park. Documenting the culture one trick at a time.', city: 'Portland', maritalStatus: 'Unmarried', dateOfBirth: '1998-11-28', school: 'Lincoln High School', college: 'Portland Community College', university: 'Portland State University' },
  { fullName: 'Yuki Tanaka', username: 'yuki_tanaka', job: 'Concept Artist & Illustrator', bio: 'Anime-inspired character design. Commissions open.', city: 'Tokyo', maritalStatus: 'Unmarried', dateOfBirth: '1999-07-14', school: 'Hibiya High School', college: 'Tokyo Design Academy', university: 'Tokyo University of the Arts' },
  { fullName: 'Olivia Grant', username: 'olivia_grant', job: 'Senior Event Producer', bio: 'Curating unforgettable experiences. Weddings & corporate.', city: 'New York', maritalStatus: 'Married', dateOfBirth: '1993-01-20', school: 'Stuyvesant High School', college: 'Fashion Institute of Technology', university: 'New York University (NYU)' },
  { fullName: 'Rafael Santos', username: 'rafael_santos', job: 'Electronic Music Artist', bio: 'House & techno sets. Festival stages & underground clubs.', city: 'São Paulo', maritalStatus: 'Unmarried', dateOfBirth: '1994-09-09', school: 'Colégio Bandeirantes', college: 'Anhembi Morumbi College', university: 'University of São Paulo' },
  { fullName: 'Meera Kapoor', username: 'meera_kapoor', job: 'Performing Arts Choreographer', bio: 'Bharatanatyam performer & teacher. Tradition meets expression.', city: 'Delhi', maritalStatus: 'Married', dateOfBirth: '1995-08-19', school: 'Delhi Public School R.K. Puram', college: 'Lady Shri Ram College', university: 'University of Delhi' },
];

module.exports.REEL_CAPTIONS = [
  'When the vision finally clicks ✨',
  'Late night studio sessions hit different',
  'This moment changed everything for me',
  'POV: you found your new favorite scroll',
  'Still can\'t believe we pulled this off',
  'Raw, unfiltered, and exactly what I needed to share',
  'Watch till the end — trust me on this one',
  'The energy in this clip is unmatched 🔥',
  'Sharing this before I overthink it',
  'If you know, you know',
  'Built this with so much heart',
  'Your daily dose of inspiration',
  'This is what passion looks like in motion',
  'Comment where you\'re watching from!',
  'Saving this one for the replay loop',
  'New chapter, same hustle',
  'Grateful for every view and every share',
  'Tried something completely new here',
  'The details make all the difference',
  'One of my favorite pieces I\'ve ever made',
  'Let me know what you think in the comments',
  'Weekend vibes only',
  'Creating without limits — that\'s the goal',
  'This took weeks but worth every second',
  'Tag someone who needs to see this',
  'Behind the magic, there\'s a lot of work',
  'Still obsessed with how this turned out',
  'Motion, mood, and a little bit of chaos',
  'Dropping this for the culture',
  'Every frame tells a story',
  'Can\'t stop watching this on repeat',
  'Thanks for being part of this journey 🙏',
];

module.exports.COMMENT_POOL = [
  'This is actually really good 🔥',
  'Love this!',
  'Where was this filmed?',
  'The quality on this is insane',
  'Needed this today, thank you',
  'How long did this take you?',
  'Sharing this with my friends rn',
  'The vibes are immaculate',
  'You never miss!',
  'This deserves way more views',
  'Okay but HOW?!',
  'Instant save 📌',
  'Your best work yet',
  'The soundtrack choice is perfect',
  'Watching this on loop',
  'So much talent in one clip',
  'This made my morning',
  'Can you do a tutorial on this?',
  'Absolutely stunning work',
  'The attention to detail 👏',
  'Following for more content like this',
  'This is why I love this platform',
  'Chef\'s kiss 🤌',
  'No notes, perfect',
  'The transitions are so smooth',
  'Goals right here',
  'This energy >>',
  'Respect for the craft',
  'Bookmarked for later',
  'You\'re underrated fr',
];

module.exports.POST_TEMPLATES = [
  { type: 'text', content: 'Grateful for another day to create and connect with this amazing community.' },
  { type: 'text', content: 'Small progress every day adds up. Keep showing up for yourself.' },
  { type: 'text', content: 'Behind every polished post is a lot of messy drafts. Embrace the process.' },
  { type: 'text', content: 'Collaboration over competition. DM me if you want to work together.' },
  { type: 'text', content: 'Throwback to one of my favorite projects this year.' },
  { type: 'text', content: 'Weekend mood: slow mornings, good coffee, and creative flow.' },
  { type: 'text', content: 'Question for you all — what should I create next?' },
  { type: 'image', content: 'Golden hour never disappoints.', imageSeed: 'sunset' },
  { type: 'image', content: 'Studio setup for today\'s session.', imageSeed: 'workspace' },
  { type: 'image', content: 'Exploring new corners of the city.', imageSeed: 'city' },
  { type: 'image', content: 'Details matter.', imageSeed: 'detail' },
  { type: 'image', content: 'Fresh inspiration from this morning walk.', imageSeed: 'nature' },
  { type: 'multi', content: 'Swipe through — pick your favorite frame.', imageSeeds: ['frame1', 'frame2', 'frame3'] },
];
